apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-scaleout-app-hpa
  namespace: springboot-prj-myapp
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-spring-boot-docker-deployment
  targetCPUUtilizationPercentage: 30
