kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: springboot-prj-myapp
  name: hpa-patcher
rules:
  - apiGroups: ["*"]
    resources: ["horizontalpodautoscalers"]
    verbs:
      - patch
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: patch-hpa
  namespace: springboot-prj-myapp
subjects:
  - kind: ServiceAccount
    name: default
    namespace: springboot-prj-myapp
roleRef:
  kind: Role
  name: hpa-patcher
  apiGroup: rbac.authorization.k8s.io
