apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: private-reg-container-myapp
    image: privateregistry:5000/myapp:latest
  imagePullSecrets:
  - name: private-docker-regcred
